#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ryu
Version  : 4.27
Release  : 16
URL      : https://files.pythonhosted.org/packages/c8/f7/21b5a656646de0329241d8449098205494273c8c54389fee46a75a57dcb8/ryu-4.27.tar.gz
Source0  : https://files.pythonhosted.org/packages/c8/f7/21b5a656646de0329241d8449098205494273c8c54389fee46a75a57dcb8/ryu-4.27.tar.gz
Summary  : Component-based Software-defined Networking Framework
Group    : Development/Tools
License  : Apache-2.0 MIT
Requires: ryu-bin
Requires: ryu-python3
Requires: ryu-data
Requires: ryu-license
Requires: ryu-python
Requires: eventlet
Requires: msgpack
Requires: netaddr
Requires: oslo.config
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : pbr
Patch1: 0001-change-default-to-usr-share-defaults-ryu.patch

%description
==========
        Ryu is a component-based software defined networking framework.
        
        Ryu provides software components with well defined API that make it
        easy for developers to create new network management and control
        applications. Ryu supports various protocols for managing network
        devices, such as OpenFlow, Netconf, OF-config, etc. About OpenFlow,
        Ryu supports fully 1.0, 1.2, 1.3, 1.4, 1.5 and Nicira Extensions.
        
        All of the code is freely available under the Apache 2.0 license. Ryu
        is fully written in Python.
        
        
        Quick Start
        ===========

%package bin
Summary: bin components for the ryu package.
Group: Binaries
Requires: ryu-data
Requires: ryu-license

%description bin
bin components for the ryu package.


%package data
Summary: data components for the ryu package.
Group: Data

%description data
data components for the ryu package.


%package doc
Summary: doc components for the ryu package.
Group: Documentation

%description doc
doc components for the ryu package.


%package license
Summary: license components for the ryu package.
Group: Default

%description license
license components for the ryu package.


%package python
Summary: python components for the ryu package.
Group: Default
Requires: ryu-python3

%description python
python components for the ryu package.


%package python3
Summary: python3 components for the ryu package.
Group: Default
Requires: python3-core

%description python3
python3 components for the ryu package.


%prep
%setup -q -n ryu-4.27
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533874122
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/ryu
cp LICENSE %{buildroot}/usr/share/doc/ryu/LICENSE
cp debian/copyright %{buildroot}/usr/share/doc/ryu/debian_copyright
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## install_append content
install -d -m 755 %{buildroot}/usr/share/defaults/ryu
install -p -D -m 644 etc/ryu/ryu.conf %{buildroot}/usr/share/defaults/ryu/
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ryu
/usr/bin/ryu-manager

%files data
%defattr(-,root,root,-)
/usr/share/defaults/ryu/ryu.conf

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/ryu/*

%files license
%defattr(-,root,root,-)
/usr/share/doc/ryu/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
