#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ryu
Version  : 4.34
Release  : 32
URL      : https://files.pythonhosted.org/packages/25/30/1c1972b3f9bf52de32d2fdf7c5206ff7099e739bf69b6004f4a71bcbde18/ryu-4.34.tar.gz
Source0  : https://files.pythonhosted.org/packages/25/30/1c1972b3f9bf52de32d2fdf7c5206ff7099e739bf69b6004f4a71bcbde18/ryu-4.34.tar.gz
Summary  : Component-based Software-defined Networking Framework
Group    : Development/Tools
License  : Apache-2.0
Requires: ryu-bin = %{version}-%{release}
Requires: ryu-data = %{version}-%{release}
Requires: ryu-license = %{version}-%{release}
Requires: ryu-python = %{version}-%{release}
Requires: ryu-python3 = %{version}-%{release}
Requires: Routes
Requires: eventlet
Requires: msgpack
Requires: netaddr
Requires: oslo.config
Requires: ovs
Requires: six
Requires: tinyrpc
BuildRequires : Routes
BuildRequires : buildreq-distutils3
BuildRequires : eventlet
BuildRequires : msgpack
BuildRequires : netaddr
BuildRequires : oslo.config
BuildRequires : ovs
BuildRequires : pbr
BuildRequires : six
BuildRequires : tinyrpc
Patch1: 0001-change-default-to-usr-share-defaults-ryu.patch

%description
==========
        Ryu is a component-based software defined networking framework.
        
        Ryu provides software components with well defined API's that make it
        easy for developers to create new network management and control
        applications. Ryu supports various protocols for managing network
        devices, such as OpenFlow, Netconf, OF-config, etc. About OpenFlow,
        Ryu supports fully 1.0, 1.2, 1.3, 1.4, 1.5 and Nicira Extensions.
        
        All of the code is freely available under the Apache 2.0 license. Ryu
        is fully written in Python.
        
        
        Quick Start
        ===========

%package bin
Summary: bin components for the ryu package.
Group: Binaries
Requires: ryu-data = %{version}-%{release}
Requires: ryu-license = %{version}-%{release}

%description bin
bin components for the ryu package.


%package data
Summary: data components for the ryu package.
Group: Data

%description data
data components for the ryu package.


%package license
Summary: license components for the ryu package.
Group: Default

%description license
license components for the ryu package.


%package python
Summary: python components for the ryu package.
Group: Default
Requires: ryu-python3 = %{version}-%{release}

%description python
python components for the ryu package.


%package python3
Summary: python3 components for the ryu package.
Group: Default
Requires: python3-core
Provides: pypi(ryu)
Requires: pypi(eventlet)
Requires: pypi(msgpack)
Requires: pypi(netaddr)
Requires: pypi(oslo.config)
Requires: pypi(ovs)
Requires: pypi(routes)
Requires: pypi(six)
Requires: pypi(tinyrpc)
Requires: pypi(webob)

%description python3
python3 components for the ryu package.


%prep
%setup -q -n ryu-4.34
cd %{_builddir}/ryu-4.34
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1590681629
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ryu
cp %{_builddir}/ryu-4.34/LICENSE %{buildroot}/usr/share/package-licenses/ryu/2b8b815229aa8a61e483fb4ba0588b8b6c491890
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## install_append content
install -d -m 755 %{buildroot}/usr/share/defaults/ryu
install -p -D -m 644 etc/ryu/ryu.conf %{buildroot}/usr/share/defaults/ryu/
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ryu
/usr/bin/ryu-manager

%files data
%defattr(-,root,root,-)
/usr/share/defaults/ryu/ryu.conf

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ryu/2b8b815229aa8a61e483fb4ba0588b8b6c491890

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
